# Generated by Django 5.2.9 on 2025-12-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "event_date",
                    models.CharField(
                        help_text="Ex: 'Maio 2025' ou 'Toda 1ª e 3ª Sexta'",
                        max_length=100,
                        verbose_name="Data (texto)",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("exclusivo", "Exclusivo (Alunos CEFET-MG)"),
                            ("quinzenal", "Encontro Quinzenal"),
                        ],
                        default="aberto",
                        max_length=50,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "delegates_expected",
                    models.CharField(
                        blank=True,
                        help_text="Ex: '200+' ou '50'",
                        max_length=50,
                        verbose_name="Delegados",
                    ),
                ),
                (
                    "registration_open",
                    models.BooleanField(
                        default=False, verbose_name="Inscrições Abertas"
                    ),
                ),
                (
                    "registration_url",
                    models.URLField(blank=True, verbose_name="Link de Inscrição"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Título/Descrição"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("evento", "Eventos"),
                            ("bastidores", "Bastidores"),
                            ("produto", "Produtos"),
                        ],
                        default="evento",
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="gallery/", verbose_name="Imagem"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JoinInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("equipe", "Equipe"),
                            ("diretor", "Diretor de Comitê"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Formulário",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "course_year",
                    models.CharField(
                        max_length=200, verbose_name="Curso/Ano/Instituição"
                    ),
                ),
                ("motivation", models.TextField(verbose_name="Motivação")),
                (
                    "experience",
                    models.TextField(blank=True, verbose_name="Experiência Prévia"),
                ),
                (
                    "cv",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="cvs/",
                        verbose_name="CV (Opcional)",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="partner_logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("website_url", models.URLField(blank=True, verbose_name="Website")),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("content", models.TextField(verbose_name="Conteúdo")),
                (
                    "published_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Publicação"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome do Produto"),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Preço (R$)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Imagem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("role", models.CharField(max_length=100, verbose_name="Cargo")),
                ("bio", models.TextField(blank=True, verbose_name="Bio Curta")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Use uma foto 400x400. Use placehold.co para placeholders.",
                        null=True,
                        upload_to="team_photos/",
                        verbose_name="Foto",
                    ),
                ),
            ],
        ),
    ]
